### ISSUE TITLE
Task List - Ongoing

### ISSUE THREAD

**Issue by jodiegardiner** [energy-data/energydata.info#275]
Here is a list of outstanding tasks to do with the site redesign and further features.

Current task list:

- [x] Remove the white space at the bottom of the page for the homepage to look consistent on various monitors.  
- [x] Modify the interactive map to perform like the Rise Map: 1) clickable countries to access datasets 2) pop-ups should not block the underneath and surrounding countries.
- [x] Revert the NASA base layer and change the color of the interactive map to ENERGYDATA blue.
- [x] Remove the search bar from the header on the homepage and add a space holder in its place. The search bar in the header will remain accessible on pages other than the homepage.
- [x] Reduce the box size of the Most Viewed Data and feature most popular apps or liked datas.
- [x] Carousel slider arrows bigger
- [x] Most viewed box fix size
- [x] Footer whitespace
- [x] Footer overlap content
- [x] Replace “X datasets found” to read “X datasets” 
- [x] Completely remove facets for “Groups” and “Published Date”.
- [x] Remove “Countries” and “Topics” facets from the left side menu and add them as expandable selection boxes above the main search bar. Expandable boxes should organize countries and topics by alphabetical order, with the number of datasets listed next to each country. Users should be able to search by typing keywords and select multiple tags (only list the countries covered by ENERGYDATA datasets). 
- [x] Add both vocabulary lists as helper functions
- [x] Pull into template
- [x] Make clickable link to all datasets from that vocab
- [x] Move “Add Dataset” to the right 
- [x] Move hex-two front-page to old staging to avoid looking at two diff sites for feedback/review
- [x] ~Allow customisation of boxes on front page by sysadmin~ EEX to provide text/images, Derilinx to implement on demand.
- [x] Map - ~awaiting tile layer url and smaller geojson (EEX to provide)~ 
- [x] Map - Implement WB provided tile layer (blue map)
- [x] Map - convert to use WB provided geojson

Not site design related
- [x] NRGI linkage - ckan to ckan harvester
- [x] Upload resources to the file store for 38 WB org datasets
- [x] Metadata - allow datasets to be private (https://github.com/energy-data/energydata.info/issues/274)

+ Outstanding tickets in this repo.

**Comment by jodiegardiner** [comment]
- [x] Make logo bigger
- [x] Make the logo vertically centred aligned
- [x] Menu aligned vertically and horizontally
- [x] Icons split into columns
- [x] Make Most Viewed same as Recently Added - Blue header, bold, white text, all caps.
- [x] Remove "View App" from carousel
- [x] Energydata team to send content for Recently Added section
- [x] move carousel dots up
- [x] make map show less antarctica
- [x] footer too wide - horizontal scroll
- [x] remove pointer from map popups.  Investigate position of popup
- [x] more linespacing on map popup
- [x] change map border colours to grey to match the Sea
- [x] unstick footer 
- [x] fix whitespace issue that will arise again.
- [x] "Active" menu item background.
- [x] Prevent horizontal scroll on some screen sizes

**Comment by jodiegardiner** [comment]
- [x] Connect to newly provided map layer from Bruno
- [x] Change layer colour to baby blue.
- [x] Stack the “feature” and “most viewed dataset” box on top of each other. Both boxes will be rotational and feature up to 3 slides. The Most Viewed box wil feature the top 3 datasets. We will provide you with images for the boxes.
- [x] Create some space/a banner for a map title:”Explore data by country”, so the map does not look cut-off by the content above. We can now have up to a map length of scrolling space.
- [x] Keep the current ENERGYDATA search bar banner (production), enlarge and strech in size 2) place the new search bar section (staging) on the top and under the catch phrase (Example in the attachement)
- [x] For the country shapefile color, we would like to try the color: R137 G207 B240. The dark blue background for icons is a bit bold for the page. Please experiment with the colors. Perhaps variations of the ENERGYDATA blue such as R48 G177 B225 or R20 G167 B221 etc.
- [x] Rearrange homepage as per document via email
- [x] hero 2/3rds page width, sliders 1/3rd
- [x] left hand column tidied up
- [x] blue bg for super hero box
- [x] add newly provided logo to footer
- [x] add hero text back in from existing site
- [x] change search box back to old design
- [x] color match with energy data blue - get color wheel
- [x] popups offset and disappear after a few seconds

**Comment by jodiegardiner** [comment]
Color wheel suggestion from Adobe:

![Screenshot 2019-05-13 at 12 27 08](https://user-images.githubusercontent.com/21362845/57618236-c69abb80-757a-11e9-828f-13393bc69b7e.png)

"Energydata Blue" on the left with suggested complimentary colors.  I used the second color for the icon bar on the new homepage.
